### ISSUE TITLE
vw server not starting , giving RPC import error

### ISSUE THREAD

**Issue by shivam05011996** [deep-compute/vwserver#4]
- I tried installing vwserver and it got installed.
- But when I tried to execute -
```vwserver run --port 8889 data which vw```,  it throwed error as -
```Traceback (most recent call last):
  File "/usr/local/bin/vwserver", line 9, in <module>
    load_entry_point('vwserver==0.1', 'console_scripts', 'vwserver')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/vwserver/__init__.py", line 1, in <module>
    from vwserver import VWSocket, VW, VWAPI, VWClient, VWServer
  File "/usr/local/lib/python2.7/dist-packages/vwserver/vwserver.py", line 18, in <module>
    from funcserver import RPCServer, RPCClient
ImportError: cannot import name RPCServer
```
Output of `vw`
```
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features

    n.a.     n.a.            1            1.0  unknown   0.0000        1

    n.a.     n.a.            2            2.0  unknown   0.0000        1


```

**Comment by chatrapathik** [comment]
@shivam-deepcompute There is a mistake in our run command 
```
vwserver run --port 8889 data which `vw`
```
- We tried by running the above command, It works fine as expected without raising any error.
- Can you please check it once and close this ticket. Thanks!

**Comment by shivam05011996** [comment]
@chatrapathik , we should also update the README.md file, so that it is not confusing.
